CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    address TEXT NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT NOW(),
    update_time TIMESTAMP,
    value_text_search TSVECTOR
);

CREATE UNIQUE INDEX IF NOT EXISTS members_shop_id_phone_idx ON members (shop_id, phone);

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE EXTENSION IF NOT EXISTS btree_gin;

CREATE INDEX IF NOT EXISTS members_shop_id_value_text_idx ON members USING GIN (shop_id, value_text_search);

CREATE OR REPLACE FUNCTION members_upsert_search_trigger() RETURNS trigger AS
$$
BEGIN
    new.value_text_search := TO_TSVECTOR(new.id || ' ' || new.shop_id || ' ' || new.name || ' ' || new.phone);
    RETURN new;
END
$$ LANGUAGE plpgsql;

BEGIN;

DROP TRIGGER IF EXISTS members_upsert_search ON members;

CREATE TRIGGER members_upsert_search BEFORE
INSERT
    OR
UPDATE
    ON members FOR EACH ROW EXECUTE PROCEDURE members_upsert_search_trigger();

COMMIT;