CREATE TABLE IF NOT EXISTS product_sales_stats_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    date_sold DATE NOT NULL,
    product_id BIGINT NOT NULL,
    total_sold BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT NOW(),
    update_time TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS shop_id_date_sold_product_id_idx ON product_sales_stats_daily (shop_id, date_sold, product_id);