CREATE TABLE IF NOT EXISTS sales_head (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    invoice VARCHAR(30) NOT NULL,
    user_id BIGINT NOT NULL,
    total_item INT NOT NULL DEFAULT 0,
    total_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_purchase NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_tax NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_discount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_pay NUMERIC(10, 2) NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT NOW(),
    update_time TIMESTAMP
);

CREATE INDEX IF NOT EXISTS sales_head_shop_id_create_time_idx ON sales_head (shop_id, (create_time :: date));

CREATE UNIQUE INDEX IF NOT EXISTS sales_head_shop_id_invoice_user_id_idx ON sales_head (shop_id, invoice, user_id);