CREATE TABLE IF NOT EXISTS sales_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    invoice VARCHAR(30) NOT NULL,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    unit_id BIGINT NOT NULL,
    unit_name VARCHAR(30) NOT NULL,
    barcode VARCHAR(15) NOT NULL DEFAULT '0',
    ppn BOOLEAN NOT NULL DEFAULT FALSE,
    qty INT NOT NULL DEFAULT 0,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    purchase NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT NOW(),
    update_time TIMESTAMP
);

CREATE INDEX IF NOT EXISTS sales_detail_shop_id_barcode_idx ON sales_detail (shop_id, barcode);

CREATE INDEX IF NOT EXISTS sales_detail_shop_id_product_id_idx ON sales_detail (shop_id, product_id);

CREATE INDEX IF NOT EXISTS sales_detail_shop_id_create_time_idx ON sales_detail (shop_id, (create_time :: DATE));

CREATE INDEX IF NOT EXISTS sales_detail_shop_id_invoice_user_id_idx ON sales_detail (shop_id, invoice, user_id);