CREATE TABLE IF NOT EXISTS stores
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain      VARCHAR(30) NOT NULL,
    name        VARCHAR(50) NOT NULL,
    address     TEXT        NOT NULL DEFAULT '',
    phone       VARCHAR(15) NOT NULL DEFAULT '',
    create_time TIMESTAMP   NOT NULL DEFAULT NOW(),
    update_time TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS stores_domain_idx ON stores (domain);