CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL DEFAULT 0,
    user_name VARCHAR(30) NOT NULL,
    full_name VARCHAR(255) NOT NULL DEFAULT '',
    password VARCHAR(255) NOT NULL DEFAULT '',
    is_admin bool NOT NULL DEFAULT false,
    create_time TIMESTAMP NOT NULL DEFAULT NOW(),
    update_time TIMESTAMP,
    value_text_search TSVECTOR
);

CREATE UNIQUE INDEX IF NOT EXISTS shop_id_user_name ON users (shop_id, user_name);

CREATE INDEX IF NOT EXISTS user_is_admin ON users (user_name, is_admin);

CREATE OR REPLACE FUNCTION users_upsert_search_trigger() RETURNS trigger AS
$$
BEGIN
    new.value_text_search := TO_TSVECTOR(new.id || ' ' || new.shop_id || ' ' || new.user_name || ' ' || new.full_name);
    RETURN new;
END
$$ LANGUAGE plpgsql;

BEGIN;

DROP TRIGGER IF EXISTS users_upsert_search ON users;

CREATE TRIGGER users_upsert_search BEFORE
    INSERT
    OR
    UPDATE
    ON users FOR EACH ROW EXECUTE PROCEDURE users_upsert_search_trigger();

COMMIT;

-- password : admintoko123
INSERT INTO
    users (
        shop_id,
        user_name,
        full_name,
        password,
        is_admin,
        create_time,
        update_time
    )
VALUES
    (
        1,
        'admin',
        'Super Admin',
        '$2a$10$2fKbn9YBTMnLu.c5WhzjBOJAxlqcLUiznLHZ783zBE6TBmVvmasKG',
        true,
        '2022-07-22 02:36:31.189328',
        null
    ) ON CONFLICT DO NOTHING;